### ISSUE TITLE
Search with lazyload is very slow at start

### ISSUE THREAD

**Issue by duzun** [vakata/jstree#1056] opened 2015-03-26 13:53 UTC
I have a jstree with 450 nodes loaded asynchronously.
When I do a search that loads almost/maybe all nodes, it takes about one minute before `.search.jstree` is triggered.
After first search, consequent searches run in under one second.
If I first `.load_all()`, then run seach, it runs under 1 sec., which means loading of nodes is very slow.
The data is loaded from memory, so the time is spent mostly inside jstree.

My first guess is that DOM is the bottleneck, as jstree adds each node one by one to the DOM.

I see two posible solutions:
1. to improve the speed, it would be better to add a list of nodes to the DOM at once, instead of adding node by node.
2. to improve user experience, it would be nice to have interactive search, which would display search results as it loads the nodes asynchronously (now it loads everything first then starts the search).

My specs: CPU i7, 8Gb RAM, Chrome 41.0.2272.101.

**Comment by vakata** [comment] 2015-03-26 15:36
Have you tried the `massload` plugin, added in 3.1.0? It should load all nodes at once. Also there are a few speed improvements in 3.1.0, so if you are not using it - please try it. 

As for the suggestions:
1) Currently the nodes are first loaded and then appended to the DOM, so there is nothing much I can do, except use a DOM fragment or a clone of the tree, and swap the original tree - unfortunately, I recently tried this approach and it did not yield a better result.

2) I will definitely think about that, but first let me know if massload changes the situation.

Best regards,
Ivan

**Comment by duzun** [comment] 2015-03-26 15:53
I actually switched to v3.1.0 and did the tests before openning this issue ticket.

I will try massload plugin and let you know how it works.

I would have to massload at search, after I decided which nodes to load, but before the actual search starts, because search loads the nodes automatically, is that right?

**Comment by vakata** [comment] 2015-03-26 16:46
`massload` hooks into the core `_load_nodes` function (which the search plugin uses). 

You only have to include the plugin in your `plugins` config option and configure it (if you are using AJAX - define an endpoint for the plugin to use, if you are using a function - define a new function that will fetch all the nodes at once), no other work is necessary - no need to modify the search config in any way.

What massload does is it replaces a whole lot of AJAX (or function calls) with a single AJAX request (or a function call).

Here is an example config:
```js
$('#tree').jstree({
	'core' : {
		'data' : {
			'url' : "api/node",
			'data' : function (node) {
				return { 'id' : node.id };
			}
		},
	},
	'massload' : {
		'url' : "api/nodes",
		'data' : function (ids) {
			return { 'id' : ids.join(',') };
		}
	},
	plugins : ['massload']
});
```
In the above example, if you search for a node and the nodes needed by the search plugin are `["node1","node2"]`
jsTree will make a request to `api/nodes?id=node1,node2` expecting a result which has each of those IDs and it's children (much like what you return to populate the tree):
```
{
  "node1" : [ {"id":"node3","text":"Some child of Node 1"}, {"id":"node2","text":"Node 2","children":true} ],
  "node2" : [  {"id":"node4","text":"Some child of Node 2"} ],
}
```

Let me know how it goes, if there is not enough improvement - could you please share your config, so that I can debug and find the cause of this.

Best regards,
Ivan

**Comment by duzun** [comment] 2015-03-26 18:03
I've tried massload. It did improve a little bit search experience, but not that much.

Here are the results:

With massload plugin:
1. in **25ms** `.search.ajax()` matches **122** nodes and returns **66** node ids to be open by jstree;
2. in **39676ms** `.massload()` fetches and prepares a total of **394** child-nodes for the **66** parent-nodes;
3. in **1300ms** jstee matches the **122** nodes using `.search.search_callback()`.

Without massload plugin everything is the same, except:
2. in **40126ms** jstree loads nodes using `.core.data()` callback.

Some other notes:

On first search, jstree uses massload plugin, but on next searches it uses `.core.data()` instead, like massload is not enabled.

Sometimes search with `.search.show_only_matches = true` show nodes that do not match the search string. I guess it is because the nonmatching node is loaded later, after the search filtered the results.

**Comment by duzun** [comment] 2015-03-26 18:14
Thanks for support @vakata !

I'm still guessing most of the time is spent with DOM manipulation or DOM traversal. 

Regards

**Comment by vakata** [comment] 2015-03-26 19:09
Yes, DOM is definitely a big part of it, although it is a bit odd - in my tests jstree runs with 30.000 nodes (I admin a bit sluggish), but 400 nodes should not cause such a huge delay.
You can try and disable `core.worker` - that will definitely speed things up (at least it usually does), but rendering will block the main thread. 

In the mean time - I will set up a test case and try to hunt this down.

Regards,
Ivan

**Comment by duzun** [comment] 2015-03-26 19:25
I disabled the worker and now it loads in about 1 sec.
It is strange to me, as I'm using callbacks instead of AJAX, and data is already a JS Object, not a JSON string. So what is the point of using workers in my case?
It is true, the UI blocks for a second or two, but I don't have to wait for a minute.

**Comment by vakata** [comment] 2015-03-26 20:44
Hi again,
The point of the workers is to do the heavy lifting (transforming the data to the required jstree format) off the main thread. Unfortunately all the back and forth passing of the huge model object is a bit sluggish sometimes - it works wonders for large trees which are parsed as a whole, but it sucks at incremental parsing.

I will see if I can improve on that (workers). I am closing this ticket now, right? If you profile this you will probably find the second or two is spent in DOM operations, I doubt it can be improved much.

Best regards,
Ivan

**Closed by vakata** 2015-03-26 20:44 UTC

**Comment by duzun** [comment] 2015-03-26 20:55
For my usecase (search+lazyload+workers), in the case there is a realy big dataset and I wanna use workers, I think it would be perfect to have interactive search, which would display search results as it loads the nodes asynchronously.
Otherwise I see it as a different issue - workers performance...

Thanks again and all the best!

**Comment by vakata** [comment] 2015-03-26 22:56
Thanks for the input and all the help, I will give interactive search some thought, as it will be a major change to the plugin and will probably change the way search events fire. 
As for the workers - I am on it.

Best regards,
Ivan

**Comment by Magnil** [comment] 2015-12-20 02:41
I met the same problem with duzun. The massload plugin only works on first search, but on next searches it uses `.core.data()` instead.

My config is like (I just copied the first demo on your jstree homepage):
```javascript
            $(function () {
              var to = false;
              $('#demo_q').keyup(function () {
                if(to) { clearTimeout(to); }
                to = setTimeout(function () {
                  var v = $('#demo_q').val();
                  $('#jstree_demo').jstree(true).search(v);
                }, 1000);
              });

              $('#jstree_demo')
                .jstree({
                  "core" : {
                    "animation" : 0,
                    "check_callback" : true,
                    'force_text' : true,
                    "themes" : { "stripes" : true },
                    'data' : {
                      "url" : function(node) {
                        if( node.id == -1 ){
                          return "/customize/get";
                        } else {
                          return "/customize/get/" + node.id;
                        }
                      },
                      "dataType" : "json"
                    }
                  },
                  "search": {
                      "ajax": {
                        "url" : "/customize/search/",
                      },
                      "show_only_matches": true
                  },
                  "massload" : {
                      "url" : "/customize/massload/",
                      "data" : function (nodes) {
                        return { "ids" : nodes.join(",") };
                    }
                  },
                  "plugins" : [ "massload", "search", "state", "types", "wholerow" ]
                });
            });
```

From what I can see in the network activity, on first search, `/customize/massload/{ids}` is loaded but on next searches, it doesn't load massload url but `/customize/get/{id}`.

Any help?

**Comment by demesiooliveira** [comment] 2018-03-16 11:43
Hello Ivan,

I'm following your example for massload, however after loading the data function it does not call the massload. Is there any JSON pattern for massload to load?

```javascript
$('#turbinas-componentes').jstree({
                'core' : {
                    'data' : {
                        'url' : urlBase + 'punch-list/turbinas-componentes',
                        "dataType" : "json",
                        'data' : function (node) {
                            return { 'id' : node.id, 'type': node.type };
                        }
                    }
                },
                "massload" : {
                    "url" : urlBase + 'punch-list/teste',
                    "data" : function (ids) {
                        return { "ids" : ids};
                    }
                },
                "checkbox" : {
                    "keep_selected_style" : false
                },
                "types" : {
                    "default" : {
                        "icon" : "fa fa-home"
                    },
                    "fabricante" : {
                        "icon" : "fa fa-industry"
                    },
                    "modelo" : {
                        "icon" : "fa fa-sitemap"
                    },
                    "escopo" : {
                        "icon" : "fa fa-list"
                    },
                    "sistema" : {
                        "icon" : "fa fa-gears"
                    },
                    "componente" : {
                        "icon" : "fa fa-cube"
                    },
                },
                "plugins" : ["massload", "checkbox", "types"]
            });
```
