### ISSUE TITLE
Drag and Drop not carrying Data attribute

### ISSUE THREAD

**Issue by mutifatih** [vakata/jstree#1856] opened 2017-10-18 13:24 UTC
I have two jstree divs and i can drag and drop from one to each other.

Before I drag the node, have data attribute (data-supp="1").
After I drop the node to other jstree, node lose their data attribute. (stay in "li-attr" but data property is null)

As you can see;
<img width="1320" alt="before" src="https://user-images.githubusercontent.com/6299507/31720936-a210b21e-b420-11e7-81b5-0517934696b1.png">
<img width="1330" alt="after" src="https://user-images.githubusercontent.com/6299507/31720935-a1f39788-b420-11e7-8026-a8b400ce09ea.png">

Best Regards

**Comment by mutifatih** [comment] 2017-10-18 13:28
By the way;

When I drag and drop to same jstree, data atrribute not gone.
This bug seems when i drag and drop to other jstree.

**Comment by RamprashanthA-Hexaware** [comment] 2017-10-24 03:52
Is it possible to drag and drop in a editor from js tree?

**Comment by vakata** [comment] 2017-12-29 22:02
I can not reproduce the issue - here is the fiddle:
http://jsfiddle.net/2kwkh2uL/5807/

Please modify the fiddle so that the issue is present and I will try to fix this. I am closing this for now.

**Closed by vakata** 2017-12-29 22:02 UTC
