### ISSUE TITLE
Opening a folder by clicking on its icon does not work on latetest Firefox on **macOS**

### ISSUE THREAD

**Issue by thomasdumm** [vakata/jstree#1911] opened 2017-12-28 09:49 UTC
Opening a folder by clicking on its icon does not work on latetest Firefox on **macOS**. It still works on latest Firefox on Windows and in Google Chrome on macOS. No error message is shown in console. I was able to reproduce the issue on 2 Macs with latest Firefox.

Firefox Quantum 57.0.1 (64-Bit)
macOS High Sierra Version 10.13.2

**Comment by vakata** [comment] 2017-12-28 14:08
Could you please provide an example or a more detailed description? Which icon stopped working? Folders were never supposed to open by clicking the icon itself, just the little triangle next to the folder - did that triangle stop working?

**Comment by thomasdumm** [comment] 2017-12-28 19:42
clicking on the triangle stopped working. See screencasts:
Chrome: https://www.dropbox.com/s/4mkse3g82qj2ogv/chrome_working.mp4?dl=0
Firefox: https://www.dropbox.com/s/w88hivft34aognw/Firefox_not_working.mp4?dl=0

**Comment by vakata** [comment] 2017-12-29 06:15
Possibly a duplicate of this issue:
https://github.com/vakata/jstree/issues/1899

Make sure no plugins are messing with your browser. If this is not the case - let me know and I will reopen, but please try clearing your cache, checking for errors in the console - and just in case - running an instance with no plugins active (to rule out third party JS messing up the tree)

**Comment by thomasdumm** [comment] 2017-12-29 07:17
the issue is real and happens only on macOS. We use jstree for 3 years and had no issues up to latest Firefox.

**Comment by thomasdumm** [comment] 2017-12-29 07:20
ps: also your demo examples on the jstree homepage show the issue on macOS in Firefox. No issue in Chrome on macOS

**Comment by vakata** [comment] 2017-12-29 08:14
OK, I am reopening this but it seems like a browser issue to me. I do not own a mac so I have no way of reproducing the issue. In order for me to get a better understanding of the issue - please provide more information:
1) Did you try a clean firefox (no plugins)
2) Do you get any errors in the console

**Comment by thomasdumm** [comment] 2017-12-29 08:31
clean firefox 
no error in console

maybe try in a store where they sell macs?

**Comment by vakata** [comment] 2017-12-29 15:42
Sorry for the inconvenience but I do need all the information, so that I can get so that I can help you. As for the Mac - I am afraid I can not afford to buy one just to reproduce an issue, and debugging in a store is not possible I am afraid. I will try browserstack though - I will keep you in the loop.

**Comment by vakata** [comment] 2017-12-31 07:36
I had no problem working with the trees on jstree.com using Firefox 57.0 (64 bit) on High Sierra on two different machines (local computer shop and a BrowserStack instance).

Maybe the problem is something local and specific to your setup? Btw, is the issue resolved in 57.0.3 (which is the current version for MacOS)? 
If the issue is not with your local setup I strongly suspect that it was (or is) a browser issue, as that part of jstree is pretty simple - a DOM element with a delegated click event handler - there is literally nothing that can go wrong with that part of the code.

I will keep monitoring this and reopen the issue if I receive any other complaints.

**Closed by vakata** 2017-12-31 07:36 UTC

**Comment by thomasdumm** [comment] 2018-01-01 11:04
I was able to find the source of the problem: I had one plugin installed that is a JSON data viewer.
https://addons.mozilla.org/de/firefox/addon/mjsonviewer/
deinstalling the plugin solved the problem. I was not aware that I had this plugin installed.
So sorry for bothering you and thank you for looking into the problem that turned out to be my problem.

**Comment by vakata** [comment] 2018-01-02 08:11
No problem. It was exactly the same plugin that caused the same problem in the other issue I linked to.
