### ISSUE TITLE
Multiple Redraw and UI Thread Blockage

### ISSUE THREAD

**Issue by hadiwina** [vakata/jstree#2294] opened 2019-08-20 21:38 UTC
Hi, Thanks for the great library!

I'm looking at some performance issues on areas that are using the jstree library. I noticed that when we're loading about 5,000 root nodes, there are multiple `redraw()` being triggered. See below screenshot:

![Screen Shot 2019-08-20 at 5 33 56 PM](https://user-images.githubusercontent.com/5366783/63386510-3c2fd800-c371-11e9-9f14-15fc920282ac.png)

I'd like to confirm whether this is normal for jstree to do so, because during this time, UI is frozen for a few seconds and on our setup this looks odd because the dialog has not opened yet. It seems that the UI thread is blocked by the rendering process (`redraw()`). 

If this is not normal, are you able to point me to what might have caused this issue?

Thanks!

**Comment by vakata** [comment] 2019-09-03 08:03
Please share your config and some sample data so that I can reproduce. Sometimes it all depends on included plugins and their configuration. Normally I do not expect to see multiple redraw calls.

**Comment by vakata** [comment] 2020-02-10 22:02
Closing because no further information was provided.

**Closed by vakata** 2020-02-10 22:02 UTC
