### ISSUE TITLE
Bug with Google Chrome

### ISSUE THREAD

**Issue by jplevene** [vakata/jstree#981] opened 2015-02-02 21:51 UTC
This is evident on the Demo page (http://www.jstree.com/demo/)

Using Google Chrome, expand all the nodes on the Filebrowser demo and then click a node, then click another node.  Do not move the mouse after clicking the second node and you will see the previously selected node is still highlighted as selected and the newly clicked and selected node will not be selected until you move the mouse off of the node or double click it.

This seems an obvious Google Chrome bug as this does not happen on other browsers.

I am using Chrome version 40.0.2214.94 m on a 32bit machine with hardware acceleration enabled. Disabling hardware acceleration on Chrome made no difference.

**Comment by jplevene** [comment] 2015-02-02 21:53
I am using Version 40.0.2214.94 m on a 32bit machine with hardware acceleration enabled.

**Comment by vakata** [comment] 2015-02-02 22:24
In which OS is this? I can not reproduce (using the same version of Chrome) in Windows 8.1 (nor on any windows machine I have).

**Comment by jplevene** [comment] 2015-02-02 22:49
Windows 7. I have had similar problems with jQuery and Chrome before on 64 bit machines

**Comment by vakata** [comment] 2015-02-02 23:05
Thanks, I guess I can force a redraw, and see if that fixes it, but it is not a proper solution even if it works. I will try and reproduce and if I do I will see if a redraw fixes it and let you know.

Best regards,
Ivan

**Comment by vakata** [comment] 2015-02-04 12:08
Any news or further instructions? I tried 3 different win & machines with the above Chrome version and hardware acceleration both enabled and disabled and could not reproduce. 
I am closing this for now - let me know if you can provide further instructions on how to reproduce and I will reopen.

**Closed by vakata** 2015-02-04 12:08 UTC
