### ISSUE TITLE
contextmenu not visible

### ISSUE THREAD

**Issue by wambacher** [vakata/jstree#1958] opened 2018-03-03 15:40 UTC
you asked me to set z-level high. but this did not help :(

i debugged a little bit. The plugin is called and is running - but does not display anything.

i'm not very experienced with plugins but:

jstree.js:46 document = window.document; // local variable is always faster to access then a global

which value will/should get document? the main window or the dialog box window?

regards
walter

btw: please don't close unless the problem is solved :(

**Comment by vakata** [comment] 2018-03-04 07:00
Duplicate of #1957

**Closed by vakata** 2018-03-04 07:00 UTC
