### ISSUE TITLE
Invalid node expanded after refresh

### ISSUE THREAD

**Issue by sebasmoyano** [vakata/jstree#1793] opened 2017-07-12 18:33 UTC
To reproduce the issue:
- Create a tree that it is being updated through an AJAX call.
- Perform a delete of more than one record on server side. This records are referenced by the tree.
- Perform a refresh of the tree skipping re-loading:
`$('#treeid').jstree(true).refresh(true);`
- You will see two undesired effects related to scrolling and invalid node expansion.

**Comment by sebasmoyano** [comment] 2017-07-12 18:51
Let me know if there is a workaround to solve this.

**Comment by vakata** [comment] 2017-07-13 04:48
Sorry, I will need a demo for this - there are way to many questions not answered here - which nodes should be deleted, should they be opened in the tree prior to deleting, should a parent node lose all its children for this to work, etc. Not to mention - which version are you using? 

Please provide a demo so that I can help.

**Comment by vakata** [comment] 2017-07-17 08:20
I am closing this for now - I will reopen when more information is available.

**Closed by vakata** 2017-07-17 08:20 UTC

**Comment by sebasmoyano** [comment] 2017-07-24 13:40
I'm using version 3.3.2 but it happens with the latest as well

![deleting_node](https://user-images.githubusercontent.com/5084534/28525734-8e63e168-705b-11e7-9930-cba9a2f5dc1a.gif)

Comments about the video:
- Pay attention to nodes called "CRUD actions". There are two different paths for same node. Different ids are used for those nodes.
- When the switcher "Allow to create" is disabled the nodes: "Contacts add" should be deleted.
-  As result of the operation the node "Contacts read only" is displayed when it shouldn't.
- Seems like the pattern is after refreshing the tree from server side and 2 or more nodes has been deleted an invalid node is expanded. Having only 1 node deleted it works as expected.

Thanks!

**Comment by vakata** [comment] 2017-07-25 08:53
Sorry, but I can not debug your application based on a video, but please read on: 

When you invoke ```refresh``` the current state is saved (this includes selected nodes, opened nodes and scroll position as well as data added by plugins). The tree is then refreshed based on what you provided in ```core.data``` (starting from the root). Once all nodes that need to be loaded are loaded the state is reapplied - nodes are reopened (based on their ID), nodes are reselected (based on their ID), scroll position is restored.

**If your nodes have the same IDs** jstree WILL NOT open a node that was not previously opened. The key here are the node IDs - they need to be the same - if the IDs change when refreshing the tree restoring the state will not work - if that is the case - you will have to rely on your server to return the state along with the nodes and make sure you call refresh with its second param set to ```true```:
https://www.jstree.com/api/#/?q=refresh&f=refresh()
I guess returning consistent IDs will be the better option.

_There is one more possibility why jstree COULD open a node - and that is if the node is selected but has closed parents._

As for scroll position - if a node is deleted (as you mentioned) it is possible that the scroll position will be off - jstree only saves the scrollTop property of its parent - if the tree is missing a few nodes it is normal that the position will shift. If you want to save the scroll position in some other way and not use the built-in restore - you can set the second param of ```refresh``` to a function - this function is used to modify the previous state before it is applied on the refreshed tree. You are free to examine the state, remove the scroll position and implement your own scroll position restore (for example using relative distance from the selected node).

Let me know if this was helpful and if I can help you further in any way.

**Comment by sebasmoyano** [comment] 2017-07-26 17:44
Both approaches didn't help me. Using same ids makes tree doesn't work as expected in some cases. 

It seems like it is bug. Could you please try to reproduce it? These are the steps:
- Create a tree with AJAX support.
- Delete 2 nodes with different tree path on server side.
- Perform a refresh by using `$('#treeid').jstree(true).refresh(true)`

**Comment by sebasmoyano** [comment] 2017-07-26 19:30
After refresh the first deleted node works as expected. The issue happened trying to restore state for second node.

**Comment by sebasmoyano** [comment] 2017-07-26 20:04
This is the state and selected node before refresh:

![state_before](https://user-images.githubusercontent.com/5084534/28641092-4f78d9fc-7224-11e7-84fa-2ebcac9f28d6.png)

This is the state and selected node after refresh:
![state_after](https://user-images.githubusercontent.com/5084534/28641111-634b6f8a-7224-11e7-9643-3ac214fb4a89.png)

As you can see in the screenshot open nodes and selected node are not matching.

**Comment by vakata** [comment] 2017-07-27 08:24
I **NEVER** suggested using duplicated IDs - this shows me you are not reading my replies carefully. 

There is something very wrong with your demo - are you using your own IDs or depending on jstree's autogenerated ones? 

It seems to me you are using autogenerated IDs which makes it absolutely impossible to sync anything to the server side. The whole idea of a state is that the same node should have the same ID after a refresh - already explained this in my previous reply.

**Comment by sebasmoyano** [comment] 2017-07-27 15:48
By settings an ID works like a charm! Thanks!

Only one small issue appeared after using IDs. When you click a specific node the scroll position is resetted. Is a known issue or misconfigured thing?

**Comment by sebasmoyano** [comment] 2017-07-27 17:30
This is what it is happening now:

![scroll](https://user-images.githubusercontent.com/5084534/28683748-16a0cb26-72d8-11e7-8b98-89acae5b601e.gif)

**Comment by sebasmoyano** [comment] 2017-08-01 13:06
Any update on this? Do you want me to create a separated issue?

**Comment by vakata** [comment] 2017-08-02 04:45
jsTree will not modify the scroll position on select - if there is any movement - that is because of something you are doing in your own code. If you want me to help further - please provide an isolated jsfiddle for this, like this one (where the scroll is not moving as you can see): http://jsfiddle.net/2kwkh2uL/6228/

Feel free to modify this fiddle until you reproduce your issue - then I can help.

**Comment by sebasmoyano** [comment] 2017-08-02 18:40
Weird issue. I was able to fix the issue by removing the character `/` from id.

**Comment by sebasmoyano** [comment] 2017-08-02 18:40
So everything is working as expected now. Thanks!
