### ISSUE TITLE
create_node populates the children_d array incorrectly.

### ISSUE THREAD

**Issue by Jezza** [vakata/jstree#2101] opened 2018-09-10 08:53 UTC
Heyo,
just a quick clarification, and possible a bug report.

`children_d` seems to have no documented order.
From what I could tell, and from how I've always used it, it was a depth-first search result array thing.

It's really helpful, and if that is the intended order, then there's a bug in `_parse_model_from_json`.

Specifically [here](https://github.com/vakata/jstree/blob/master/src/jstree.js#L2282-L2291).

When you concat children nodes to the list, you concat them in a depth first pattern, but the wrong kind of depth first pattern.
It's concatenating it in a post-depth first pattern, and not pre-depth first.

As in it's adding the children of a node, before adding the node.
This leads to some inconsistent `children_d` arrays.
We ran into this problem when copying a node.
We're using jstree's buffer functionality. (copy, paste, etc)

![selection_027](https://user-images.githubusercontent.com/4224088/45286965-6f25e680-b4e7-11e8-8429-2d17b883c61c.png)

If you copy `Folder 1`, and then copy it to `Drive`, and listen to the `copy_node` event that is fired, you'll see the `children_d` array contains out of order data.

**Comment by Jezza** [comment] 2018-09-10 08:56
I might be wrong, but you might be able to fix it by just concatenating the children elements first.

https://github.com/vakata/jstree/blob/master/src/jstree.js#L2291

`tmp.children_d = tmp.children.concat(tmp.children_d);`

**Comment by Jezza** [comment] 2018-09-10 09:39
As I was trying to make this jsFiddle, I think I came across another bug.

http://jsfiddle.net/2Jg3B/1951/

I could just be doing something incorrect, but I'm trying to copy `Child 1` to `Drive` and it's failing with "Moving parent inside child".
If you change the `j1_2` id to one of the sub-ids such as `j1_3`, it works without issue.

**Comment by Jezza** [comment] 2018-09-10 10:03
Ok, so I finally got the jsfiddle working: http://jsfiddle.net/2Jg3B/1961/

Weirdly, it does show consistent behaviour.
Not what I thought, as it does in fact use a post-depth pattern, whereas I expected it to be pre-depth.
But all of that doesn't matter, I only expected that because one the nodes was post-depth.

But as long as it's consistent, it's fine.

But that means that the original node loses its order.

I inserted the test code into our system, and we get back something like:
https://gist.github.com/Jezza/93e3eb05934ab4df7e41e1686ab49d00

As you can probably see, the order in the jsfiddle is:

Item
Child 3

Item
Child 3


Whereas the log we're getting back is something akin to:

Item
Child 3

Child 3
Item



We don't write to the children_d array, and the only place we read it is during the `copy_node` event.

**Comment by vakata** [comment] 2018-09-10 10:26
```children_d``` has no particular order - do not expect or reply on it to have one.

**Comment by Jezza** [comment] 2018-09-10 10:40
Well, then if I can't rely on it, I need some way to identify nodes.
Right now, I have to resort to manually copying the data from source node to target node, as I lose all information.


    function cp_data(source, target) {
        data.instance.get_node(target).data = jQuery.extend(true, {}, data.instance.get_node(source).data);
    };
    cp_data(data.original, data.node);
    for(i = 0, j = data.original.children_d.length; i < j; i++) {
        cp_data(data.original.children_d[i], data.node.children_d[i]);
    };

I remember you being the one to tell me to use `children_d`, as I needed to copy the data.

A simple idea would be to give us access to this filter: https://github.com/vakata/jstree/blob/master/src/jstree.js#L4298

`no_data: true` is the thing stopping it from working.

**Comment by vakata** [comment] 2018-09-10 13:36
Sorry - I should have clarified - when copying the two nodes will have their ```children_d``` arrays in exactly the same order, but it is not a defined order. So it is safe to use that property when copying.

**Comment by Jezza** [comment] 2018-09-10 14:07
Ok, then that must mean there's a bug somewhere, because if I print out the `children_d` of `data.node` and `data.original`, they do differ.

**Comment by vakata** [comment] 2018-09-11 07:30
I see, sorry for closing then. Can you provide a demo where copying the node results in different ```children_d``` arrays? I can not help based on the raw output you provided in the gist.

**Comment by vakata** [comment] 2018-09-17 13:07
Closing this because I can not reproduce - will reopen if new data is available.

**Comment by Jezza** [comment] 2018-09-17 13:11
Sorry, I've been a bit busy.
We ended up fixing this by just altering jstree.
I'll revert the change and see what I information I can get.

**Comment by Jezza** [comment] 2018-09-18 07:12
Alrighty, after poking around, I've narrowed the bug down to create_node.

http://jsfiddle.net/2Jg3B/2002/

**Comment by Jezza** [comment] 2018-09-18 16:06
Sweet.
Glad I could help.

**Comment by vakata** [comment] 2019-03-26 18:50
Sorry for the long delay. I hope this fixes the issue.

**Closed** 2019-03-26 18:49 UTC
