### ISSUE TITLE
Cannot read property 'core' of undefined

### ISSUE THREAD

**Issue by mohaaaaa** [vakata/jstree#1932] opened 2018-01-19 13:36 UTC
Hello,
i have problems when i want to import JSON data using the Alternative JSON format.
i create the JSON data on an external php script, but when i import it, i have a java script error  : 
 Cannot read property 'core' of undefined.

Whene i check on the console, my json is exactly as the one that you use on this exemple 
![image](https://user-images.githubusercontent.com/28730459/35153244-f779b540-fd25-11e7-8771-f72e1c356eec.png)

Do you have an idea of what is the problem ?

thank you for your help.

**Comment by vakata** [comment] 2018-01-19 13:42
This is such a general error that I am afraid I can not help without a demo of the issue - please provide a demo (jsfiddle?) and I will reopen.

**Comment by mohaaaaa** [comment] 2018-01-19 14:16
Hello, here's the link for the jsfiddle :
https://jsfiddle.net/r1n6hya0/

thank you for your help

2018-01-19 14:42 GMT+01:00 Ivan Bozhanov <notifications@github.com>:

**Comment by rajavijayasaradhi** [comment] 2018-03-20 10:56
@mohaaaaa  Parent attribute is not just a random id. It's the id of the another node. Error "read property ' core" usually comes when there is no node with a given parent id.

**Comment by vakata** [comment] 2018-03-20 11:07
As @rajavijayasaradhi mentioned - there is something wrong with your data - probably a missing parent ID.

**Comment by ArthurBorsboom** [comment] 2019-04-09 17:19
I guess I encounter the same issue.
Chromium console: Uncaught TypeError: Cannot read property 'core' of undefined at self.onmessage.

Looking at the generated self.onmessage Javascript, I can see the field with the error message is set to "Node with invalid parent". So I am guessing the data contains an invalid parent ID and this error message should have been forwarded to the GUI of the browser (somehow).

![jstree-error](https://user-images.githubusercontent.com/6639859/55820611-cb8fc980-5afb-11e9-961b-3f73a6cb9684.png)

IMHO, I believe JSTree should not crash on invalid data. It would be nicer to return an error message (invalid data, or so), ignore the node, or something else.

Do you believe JSTree should handle this type of invalid input and if so, would you mind to fix it? :) 

I have attached the generated Javascript blob.
[jstree-blob-generated-self-onmessage.js.txt](https://github.com/vakata/jstree/files/3060183/jstree-blob-generated-self-onmessage.js.txt)

If necessary, I can provide the problematic JSON file too. However, this has to be in private, since it contains company data.

**Comment by vakata** [comment] 2019-04-09 18:27
I see - this is caused by the worker - I will fix this (this is something different in the worker scope), in the mean time - either fix your data, or disable core.worker. No, I do not believe jstree should crash under any circumstances, but I did not have enough information to reproduce or debug this, what you have provided though is enough.

**Comment by ArthurBorsboom** [comment] 2019-04-09 18:33
Cool! Good to hear.
As you suggested, I should and will fix the server generated JSON data.

If I can be of any assistance, please let me know.

And for what is worth it, thanks for you efforts in building such a nice library.
I enjoy using it and for that I thank you. :)

**Comment by vakata** [comment] 2019-04-13 20:15
On further inspection - this was resolved in e719ced1f061fbfbe7c93648237114d2fa7fc9b2.

**Closed by vakata** 2019-04-13 20:15 UTC

**Comment by ArthurBorsboom** [comment] 2019-04-15 08:37
Good to hear that it has already been resolved.
I am already using the latest (released) version 3.3.7.

Do I assume correct this fix will be part of a newer release?

**Comment by vakata** [comment] 2019-04-15 10:26
Yes, I will push a release later today.
