### ISSUE TITLE
WAI-ARIA Mismatch

### ISSUE THREAD

**Issue by MarioBatusic** [vakata/jstree#1952] opened 2018-02-21 10:52 UTC
Navigating the tree with the keyboard focusses ```<a>```-tags whereas all necessary ARIA staff is noted on the parent ```<li>``` tags. 
The screenreader NVDA for example speacks neither tree levels nor the expansion state by keyboard navigating but only "Link LinkName".

Solution: Put and control ARIA markup directly on the ```<a>``` tag and set every ```<li role=presentation>```. Thanks.

**Comment by vakata** [comment] 2018-08-23 13:33
Duplicate of #1926

**Closed by vakata** 2018-08-23 13:33 UTC
