### ISSUE TITLE
replace anchor with span to stop annoying "statusbar"

### ISSUE THREAD

**Issue by v1nce** [vakata/jstree#1625] opened 2016-11-13 13:10 UTC
How difficult would it be to replace the anchors with clickable spans ?
Right now when you hover a node, chrome displays the url of the link in a popup (at bottom left).
You can test it on https://www.jstree.com/ when you hover any node in trees it displays "https://www.jstree.com/#" 
I know anchors are more semantically correct but this hides important part of my web application.

And here anchor add no values because they are always "#"

**Comment by Llorx** [comment] 2016-11-14 08:04
Duplicate of https://github.com/vakata/jstree/pull/1616

**Comment by vakata** [comment] 2016-11-14 17:45
Please read here: https://github.com/vakata/jstree/pull/1616

**Closed by vakata** 2016-11-14 17:45 UTC
