### ISSUE TITLE
Accessiblity: Up/Down arrow keys focus <a> elements and not <li role="treeitem"> elements... 

### ISSUE THREAD

**Issue by Zroon** [vakata/jstree#1492] opened 2016-06-29 16:35 UTC
I could be wrong about this but the WAI ARIA TreeView specs (https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/#TreeView) defines:

> node: An item in a tree.

...and specifies:

> Each node in a tree has the role treeitem and should be a DOM child of tree.
> 
> Up Arrow and Down arrow keys move between visible nodes. 

It's "Up Arrow and Down arrow keys move between visible nodes" that seems to be problematic.

I've tested with JAWS (http://www.freedomscientific.com/Products/Blindness/JAWS) and NVDA (http://www.nvaccess.org/) and found some unexpected behavior.

When initially entering the tree or using the up/down arrow keys I only hear the information associated with the links nested in the treeitems instead of the information about the treeitem.

For example, I hear "(link text here) link" instead of something like "Level 1 group expanded (link text here) open 3 of 5" (JAWS) or "Group expanded (link text here) expanded 3 of 5 level 1" (NVDA).

I think the reason this is happening is that focus switching is happening on the jstree-anchor link elements rather than on the jstree-node elements (i.e. elements with role="treeitem").

When the focus switch occurs, it should switch focus between elements with role="treeitem" and not anything nested within them. Otherwise the screen reader won't get the information it needs when navigating the TreeView.

As it stands jsTree only seems to be keyboard accessible and not screen reader accessible. When entering into jsTree or using the arrow keys while inside of it, I'm not hearing vital information like whether or not the current node is expanded or collapsed or what level or how many items are in the level... (...unlike when I navigate this example TreeView http://www.oaa-accessibility.org/examplep/treeview1/ which switches between treeitems and not nested links).

**Comment by vakata** [comment] 2016-06-30 06:34
At the time when I implemented the screen reader fixes the anchor approach was the recommended one, as the anchor is "focusable" by default. It was a compromise between functionality and usability - I stripped a bit of functionality, but the tree was usable with all reader/browser combinations. 

As far as I can remember - the anchor nodes are labels for the tree items, meaning that when readers catch up they are supposed to correctly make the link between label and tree item, so the current implementation may not work fully on some reader/browser combinations, but is future safe. I also believe the levels come from aria attributes and are not detected from the DOM, the problem is that I do not populate those attributes, because there was an issue with lazy loaded trees.

Anyway - this is all info I gathered a year ago - I will have a fresh look and let you know.

**Comment by Zroon** [comment] 2016-07-25 20:05
It turns out that there are a couple of issues with jsTree in terms of accessibility:

1. The aria-selected attribute isn't updating from true to false properly.
2. The tabindex isn't updating from -1 to 0 properly (focused items should have a 0 tabindex).

Someone actually modified an older version (1.0-rc1) of jsTree about three years ago to implement accessibility (https://hanshillen.github.io/jqtest/#goto_tree). This one works fine in screen readers. It might be worth looking at what they did there and see if you can match that behavior in the new version.

**Comment by vakata** [comment] 2016-07-26 05:10
Hi again, the tab-index approach is not always necessary, jstree uses the `active-descendant` approach. You can read up on it here: http://accessibleculture.org/articles/2013/02/not-so-simple-aria-tree-views-and-screen-readers/

Can you provide a demo of the selected attribute not being updated? I spent a few minutes trying to replicate a problem with `aria-selected` but could not reproduce the issue, please provide some instructions so that I have something to go on.

Best regards,

**Comment by vakata** [comment] 2016-07-26 05:15
In the mean time I will see if there is a way to move focus between the treeitems, not between the labels inside them as you suggested. That should help a lot but could potentially break a lot of code, so I will need some time to test it thoroughly.

**Comment by Zroon** [comment] 2016-07-26 14:41
If you look at the example on that page (https://github.com/vakata/jstree/issues/1492#issuecomment-235164496) under the heading "The Best Approach Example" when you use the arrow keys to move through the list, aria-selected switches between "true" and "false" depending on which node in the tree is currently focused.

I've tested the treeview example on that page in NVDA and JAWS and it works fine.

When you move through jsTree using the arrow keys, aria-selected remains false. It only changes when you click on or otherwise activate the node.

It seems when you use a combination of aria-activedescendant and a roving aria-selected attribute, treeviews work as expected in screen readers. So, I don't think you actually need to update the tabindex, as you mentioned. Though, if the aria-selected attribute isn't changing as you move through the tree, the screen reader doesn't seem to make sense out of what's happening.

**Comment by vakata** [comment] 2016-08-04 07:31
OK, now I get what you mean.

The idea behind updating only the active descendant is that the active-descendant is the "focused" node - which can be a single node only, as opposed to aria-selected - which is the selected node (and there can be many of those).

Do you think it would be wise to only allow single selection and update the aria-selected property?

**Comment by aadrian** [comment] 2016-08-04 07:59
> Do you think it would be wise to only allow single selection and update the aria-selected property?

IMHO not, and the specification should clarify this behavior, since multi-select of nodes is very very important.

**Comment by vakata** [comment] 2016-08-04 08:27
@aadrian I agree with you - thank you for the input. I guess we really need someone used to using screen readers, who can say what is expected.

**Comment by aadrian** [comment] 2016-08-04 08:48
> I guess we really need someone used to using screen readers, who can say what is expected.

Many of our applications need to be ARIA conform (so we use screen readers quite allot), but that doesn't mean to "dumb down" applications and components for all users. 

The pragmatic approach taken is to offer "compatible" functionality for screen readers too: functionality in the sense that to be able to achieve the same thing (as from the goals of the application), not necessarily to behave the same visually on the screen. So the problem is not solved at the "component" level but at the "application" level.

This is why it's important to understand what is the tree component used for, e.g.: 
  1. only navigation or 
  2. editing hierarchical data (with most plug-ins activated). 

Most available component libraries support really only case 1. but using extra libraries like https://github.com/madrobby/keymaster , applications can be augmented with extra features to achieve case 2. too. E.g. context based quick help readable by the screen readers with shortcuts for those actions from the context menus, etc..

**Comment by Zroon** [comment] 2016-08-04 13:28
@vakata I've discussed this at length with some accessibility experts I know, and from what I gather, most (if not all) screen readers don't implement "aria-activedescendant". It's good that you put it in there, it's just that most screen readers on the market (particularly the popular ones) don't pay attention to it.

What's really needed (until aria-activedescendant is widely implemented) is something on each node that indicates which is the currently focused node. That can either be aria-selected (which is used in the article) or tabindex. You also need the aria-expanded set properly, which you're already doing.

Also, when you tab into the treeview, you need to make sure that the first node is focused, and not the entire tree container.

**Comment by M7lrv** [comment] 2016-10-27 08:23
First of all, this should be a bug, when plugins: [ "contextmenu", "checkbox"], with the existence of right-click will be selected, this should be bug? If not ask if you want to avoid this problem?

**Comment by vakata** [comment] 2017-07-06 17:36
I am switching focus to v.4 now, which will have a completely different rendering (it could even include a few different renderers). So I will close this discussion for now, but I hope it will be OK to contact @Zroon & @aadrian in a week or two to discuss how to implement accessibility in the new render engines.

**Closed by vakata** 2017-07-06 17:36 UTC
Labels: enhancement
